import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import io from 'socket.io-client';
import { nanoid } from 'nanoid';
const inter = Inter({ subsets: ['latin'] });
const socket = io('http://localhost:8080');
import React, { ChangeEvent } from 'react';
import { Box, Heading } from '@chakra-ui/layout';
import { Input, Button, Text } from '@chakra-ui/react';
import { HtmlAttributes } from 'csstype';
let userName: string | null = nanoid(10);
if (typeof window !== 'undefined') userName = prompt('Enter Your Username');
// type user = {
// 	user: string;
// };
export default function Home() {
	const [message, setMessage] = React.useState<string>('');
	const [chat, setChat] = React.useState<string[]>([]);
	const handleChange = (event: ChangeEvent<HTMLInputElement>) => {
		event.preventDefault();
		// console.log(event.target.value);
		setMessage(event.target.value);
		// console.log(message);
	};
	const sendChat = (event: React.MouseEvent<HTMLButtonElement>) => {
		if (message.trim() === '') {
			return alert('Empty Message');
		}
		console.log('Button');
		console.log(message);
		event.preventDefault();
		socket.emit('chat', { message, userName });
		setMessage('');
	};
	React.useEffect(() => {
		socket.on('chat', (payload) => {
			setChat([...chat, payload]);
		});
	});
	return (
		<>
			<Head>
				<title>Chat-App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Box>
				<Box
					display={'flex'}
					justifyContent={'center'}
					mt={'50px'}
					height={'500px'}
					overflow={'scroll'}
					overflowX={'hidden'}
				>
					<Box
						width={'60%'}
						// borderWidth="1px"
						borderRadius="lg"
						// overflow="hidden"
						overflowX={'hidden'}
					>
						{chat.map((payload: any, index) => (
							<Box width={'60%'}>
								{payload.userName == userName ? (
									<Text
										mt={'20px'}
										padding={'10px'}
										key={index}
										background={'teal.100'}
										borderRadius={'lg'}
									>
										<span style={{ fontSize: '9px' }}>{payload.userName}</span>{' '}
										<br />
										{payload.message}
									</Text>
								) : (
									<Box width={'60%'} justifyContent={'right'}>
										<Text
											mt={'20px'}
											padding={'10px'}
											key={index}
											background={'whiteAlpha.200'}
											borderRadius={'lg'}
										>
											<span style={{ fontSize: '9px' }}>
												{payload.userName}
											</span>{' '}
											<br />
											{payload.message}
										</Text>
									</Box>
								)}
							</Box>
						))}
					</Box>
				</Box>
				<Box
					// height={'99vh'}
					borderRadius="lg"
					mt={'40px'}
					// overflow="hidden"
					overflowX={'hidden'}
					display={'flex'}
					justifyContent={'center'}
					alignItems={'end'}
				>
					<Box
						width={'60%'}
						borderWidth="1px"
						borderRadius="lg"
						// overflow="hidden"
						padding={'20px'}
					>
						{/* <Heading textAlign={'center'}>Demo Chat APP</Heading> */}
						<Box as="form" mt={'20px'} display={'flex'} flexDirection={'row'}>
							<Input
								placeholder="Type Message..."
								onChange={handleChange}
								type="text"
								value={message}
							></Input>
							<Button
								ml={'4px'}
								type="submit"
								name="chat"
								id="chat"
								onClick={sendChat}
							>
								Send
							</Button>
						</Box>
					</Box>
				</Box>
			</Box>
		</>
	);
}
